DROP TABLE IF EXISTS updates;
CREATE  TABLE IF NOT EXISTS updates (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  otype VARCHAR(255) NOT NULL ,
  oid VARCHAR(255) NOT NULL ,
  datetime DATETIME NOT NULL ,
  status ENUM('NEW', 'MODIFIED', 'DELETED') NOT NULL ,
);
