//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.15 at 10:35:54 PM EST 
//


package gov.nysenate.openleg.xml.committee;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{}attendancelist"/>
 *         &lt;element ref="{}bills"/>
 *         &lt;element ref="{}chair"/>
 *         &lt;element ref="{}location"/>
 *         &lt;element ref="{}meetdate"/>
 *         &lt;element ref="{}meetday"/>
 *         &lt;element ref="{}meettime"/>
 *         &lt;element ref="{}name"/>
 *         &lt;element ref="{}notes"/>
 *       &lt;/choice>
 *       &lt;attribute name="action">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="remove"/>
 *             &lt;enumeration value="replace"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "attendancelist",
    "bills",
    "chair",
    "location",
    "meetdate",
    "meetday",
    "meettime",
    "name",
    "notes"
})
@XmlRootElement(name = "committee")
public class XMLCommittee {

    protected XMLAttendancelist attendancelist;
    protected XMLBills bills;
    protected XMLChair chair;
    protected XMLLocation location;
    protected XMLMeetdate meetdate;
    protected XMLMeetday meetday;
    protected XMLMeettime meettime;
    protected XMLName name;
    protected XMLNotes notes;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String action;

    /**
     * Gets the value of the attendancelist property.
     * 
     * @return
     *     possible object is
     *     {@link XMLAttendancelist }
     *     
     */
    public XMLAttendancelist getAttendancelist() {
        return attendancelist;
    }

    /**
     * Sets the value of the attendancelist property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLAttendancelist }
     *     
     */
    public void setAttendancelist(XMLAttendancelist value) {
        this.attendancelist = value;
    }

    /**
     * Gets the value of the bills property.
     * 
     * @return
     *     possible object is
     *     {@link XMLBills }
     *     
     */
    public XMLBills getBills() {
        return bills;
    }

    /**
     * Sets the value of the bills property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLBills }
     *     
     */
    public void setBills(XMLBills value) {
        this.bills = value;
    }

    /**
     * Gets the value of the chair property.
     * 
     * @return
     *     possible object is
     *     {@link XMLChair }
     *     
     */
    public XMLChair getChair() {
        return chair;
    }

    /**
     * Sets the value of the chair property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLChair }
     *     
     */
    public void setChair(XMLChair value) {
        this.chair = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link XMLLocation }
     *     
     */
    public XMLLocation getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLLocation }
     *     
     */
    public void setLocation(XMLLocation value) {
        this.location = value;
    }

    /**
     * Gets the value of the meetdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLMeetdate }
     *     
     */
    public XMLMeetdate getMeetdate() {
        return meetdate;
    }

    /**
     * Sets the value of the meetdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLMeetdate }
     *     
     */
    public void setMeetdate(XMLMeetdate value) {
        this.meetdate = value;
    }

    /**
     * Gets the value of the meetday property.
     * 
     * @return
     *     possible object is
     *     {@link XMLMeetday }
     *     
     */
    public XMLMeetday getMeetday() {
        return meetday;
    }

    /**
     * Sets the value of the meetday property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLMeetday }
     *     
     */
    public void setMeetday(XMLMeetday value) {
        this.meetday = value;
    }

    /**
     * Gets the value of the meettime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLMeettime }
     *     
     */
    public XMLMeettime getMeettime() {
        return meettime;
    }

    /**
     * Sets the value of the meettime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLMeettime }
     *     
     */
    public void setMeettime(XMLMeettime value) {
        this.meettime = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link XMLName }
     *     
     */
    public XMLName getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLName }
     *     
     */
    public void setName(XMLName value) {
        this.name = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link XMLNotes }
     *     
     */
    public XMLNotes getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLNotes }
     *     
     */
    public void setNotes(XMLNotes value) {
        this.notes = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAction(String value) {
        this.action = value;
    }

}
