//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.15 at 10:35:54 PM EST 
//


package gov.nysenate.openleg.xml.committee;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{}attendance"/>
 *         &lt;element ref="{}name"/>
 *         &lt;element ref="{}party"/>
 *         &lt;element ref="{}rank"/>
 *         &lt;element ref="{}vote"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "attendance",
    "name",
    "party",
    "rank",
    "vote"
})
@XmlRootElement(name = "member")
public class XMLMember {

    protected XMLAttendance attendance;
    protected XMLName name;
    protected XMLParty party;
    protected XMLRank rank;
    protected XMLVote vote;

    /**
     * Gets the value of the attendance property.
     * 
     * @return
     *     possible object is
     *     {@link XMLAttendance }
     *     
     */
    public XMLAttendance getAttendance() {
        return attendance;
    }

    /**
     * Sets the value of the attendance property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLAttendance }
     *     
     */
    public void setAttendance(XMLAttendance value) {
        this.attendance = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link XMLName }
     *     
     */
    public XMLName getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLName }
     *     
     */
    public void setName(XMLName value) {
        this.name = value;
    }

    /**
     * Gets the value of the party property.
     * 
     * @return
     *     possible object is
     *     {@link XMLParty }
     *     
     */
    public XMLParty getParty() {
        return party;
    }

    /**
     * Sets the value of the party property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLParty }
     *     
     */
    public void setParty(XMLParty value) {
        this.party = value;
    }

    /**
     * Gets the value of the rank property.
     * 
     * @return
     *     possible object is
     *     {@link XMLRank }
     *     
     */
    public XMLRank getRank() {
        return rank;
    }

    /**
     * Sets the value of the rank property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLRank }
     *     
     */
    public void setRank(XMLRank value) {
        this.rank = value;
    }

    /**
     * Gets the value of the vote property.
     * 
     * @return
     *     possible object is
     *     {@link XMLVote }
     *     
     */
    public XMLVote getVote() {
        return vote;
    }

    /**
     * Sets the value of the vote property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLVote }
     *     
     */
    public void setVote(XMLVote value) {
        this.vote = value;
    }

}
