//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.15 at 10:35:54 PM EST 
//


package gov.nysenate.openleg.xml.committee;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.nysenate.openleg.xml.committee package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Message_QNAME = new QName("", "message");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.nysenate.openleg.xml.committee
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XMLLocation }
     * 
     */
    public XMLLocation createXMLLocation() {
        return new XMLLocation();
    }

    /**
     * Create an instance of {@link XMLBill }
     * 
     */
    public XMLBill createXMLBill() {
        return new XMLBill();
    }

    /**
     * Create an instance of {@link XMLVotes }
     * 
     */
    public XMLVotes createXMLVotes() {
        return new XMLVotes();
    }

    /**
     * Create an instance of {@link XMLMember }
     * 
     */
    public XMLMember createXMLMember() {
        return new XMLMember();
    }

    /**
     * Create an instance of {@link XMLParty }
     * 
     */
    public XMLParty createXMLParty() {
        return new XMLParty();
    }

    /**
     * Create an instance of {@link XMLAction }
     * 
     */
    public XMLAction createXMLAction() {
        return new XMLAction();
    }

    /**
     * Create an instance of {@link XMLSENATEDATA }
     * 
     */
    public XMLSENATEDATA createXMLSENATEDATA() {
        return new XMLSENATEDATA();
    }

    /**
     * Create an instance of {@link XMLAttendance }
     * 
     */
    public XMLAttendance createXMLAttendance() {
        return new XMLAttendance();
    }

    /**
     * Create an instance of {@link XMLRank }
     * 
     */
    public XMLRank createXMLRank() {
        return new XMLRank();
    }

    /**
     * Create an instance of {@link XMLChair }
     * 
     */
    public XMLChair createXMLChair() {
        return new XMLChair();
    }

    /**
     * Create an instance of {@link XMLSenagenda }
     * 
     */
    public XMLSenagenda createXMLSenagenda() {
        return new XMLSenagenda();
    }

    /**
     * Create an instance of {@link XMLAddendum }
     * 
     */
    public XMLAddendum createXMLAddendum() {
        return new XMLAddendum();
    }

    /**
     * Create an instance of {@link XMLMeetday }
     * 
     */
    public XMLMeetday createXMLMeetday() {
        return new XMLMeetday();
    }

    /**
     * Create an instance of {@link XMLNotes }
     * 
     */
    public XMLNotes createXMLNotes() {
        return new XMLNotes();
    }

    /**
     * Create an instance of {@link XMLWeekof }
     * 
     */
    public XMLWeekof createXMLWeekof() {
        return new XMLWeekof();
    }

    /**
     * Create an instance of {@link XMLCommittees }
     * 
     */
    public XMLCommittees createXMLCommittees() {
        return new XMLCommittees();
    }

    /**
     * Create an instance of {@link XMLName }
     * 
     */
    public XMLName createXMLName() {
        return new XMLName();
    }

    /**
     * Create an instance of {@link XMLBills }
     * 
     */
    public XMLBills createXMLBills() {
        return new XMLBills();
    }

    /**
     * Create an instance of {@link XMLPubdate }
     * 
     */
    public XMLPubdate createXMLPubdate() {
        return new XMLPubdate();
    }

    /**
     * Create an instance of {@link XMLMeetdate }
     * 
     */
    public XMLMeetdate createXMLMeetdate() {
        return new XMLMeetdate();
    }

    /**
     * Create an instance of {@link XMLMeettime }
     * 
     */
    public XMLMeettime createXMLMeettime() {
        return new XMLMeettime();
    }

    /**
     * Create an instance of {@link XMLSenagendavote }
     * 
     */
    public XMLSenagendavote createXMLSenagendavote() {
        return new XMLSenagendavote();
    }

    /**
     * Create an instance of {@link XMLCommittee }
     * 
     */
    public XMLCommittee createXMLCommittee() {
        return new XMLCommittee();
    }

    /**
     * Create an instance of {@link XMLTitle }
     * 
     */
    public XMLTitle createXMLTitle() {
        return new XMLTitle();
    }

    /**
     * Create an instance of {@link XMLVote }
     * 
     */
    public XMLVote createXMLVote() {
        return new XMLVote();
    }

    /**
     * Create an instance of {@link XMLAttendancelist }
     * 
     */
    public XMLAttendancelist createXMLAttendancelist() {
        return new XMLAttendancelist();
    }

    /**
     * Create an instance of {@link XMLSponsor }
     * 
     */
    public XMLSponsor createXMLSponsor() {
        return new XMLSponsor();
    }

    /**
     * Create an instance of {@link XMLPubtime }
     * 
     */
    public XMLPubtime createXMLPubtime() {
        return new XMLPubtime();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "message")
    public JAXBElement<String> createMessage(String value) {
        return new JAXBElement<String>(_Message_QNAME, String.class, null, value);
    }

}
