//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.15 at 10:35:54 PM EST 
//


package gov.nysenate.openleg.xml.committee;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{}committees"/>
 *         &lt;element ref="{}pubdate"/>
 *         &lt;element ref="{}pubtime"/>
 *         &lt;element ref="{}weekof"/>
 *       &lt;/choice>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "committees",
    "pubdate",
    "pubtime",
    "weekof"
})
@XmlRootElement(name = "addendum")
public class XMLAddendum {

    protected XMLCommittees committees;
    protected XMLPubdate pubdate;
    protected XMLPubtime pubtime;
    protected XMLWeekof weekof;
    @XmlAttribute(required = true)
    protected String id;

    /**
     * Gets the value of the committees property.
     * 
     * @return
     *     possible object is
     *     {@link XMLCommittees }
     *     
     */
    public XMLCommittees getCommittees() {
        return committees;
    }

    /**
     * Sets the value of the committees property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLCommittees }
     *     
     */
    public void setCommittees(XMLCommittees value) {
        this.committees = value;
    }

    /**
     * Gets the value of the pubdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLPubdate }
     *     
     */
    public XMLPubdate getPubdate() {
        return pubdate;
    }

    /**
     * Sets the value of the pubdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLPubdate }
     *     
     */
    public void setPubdate(XMLPubdate value) {
        this.pubdate = value;
    }

    /**
     * Gets the value of the pubtime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLPubtime }
     *     
     */
    public XMLPubtime getPubtime() {
        return pubtime;
    }

    /**
     * Sets the value of the pubtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLPubtime }
     *     
     */
    public void setPubtime(XMLPubtime value) {
        this.pubtime = value;
    }

    /**
     * Gets the value of the weekof property.
     * 
     * @return
     *     possible object is
     *     {@link XMLWeekof }
     *     
     */
    public XMLWeekof getWeekof() {
        return weekof;
    }

    /**
     * Sets the value of the weekof property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLWeekof }
     *     
     */
    public void setWeekof(XMLWeekof value) {
        this.weekof = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
