package gov.nysenate.openleg.legislation.member;

import gov.nysenate.openleg.legislation.committee.Chamber;

import java.util.Objects;

/**
 * Represents a person holding a specific office
 */
public class Member {
    private final Person person;

    /** Unique member id generated by the persistence layer. */
    private final Integer memberId;

    /** The legislative chamber this member is associated with. */
    private final Chamber chamber;

    /** Indicates if the member is currently an incumbent. */
    private final boolean incumbent;

    private final int personId;

    public Member(Person person, int memberId, Chamber chamber, boolean incumbent) {
        this.person = person;
        this.memberId = memberId;
        this.chamber = chamber;
        this.incumbent = incumbent;
        this.personId = person.personId();
    }

    public Member(Member member) {
        this.person = member.person;
        this.memberId = member.memberId;
        this.chamber = member.chamber;
        this.incumbent = member.incumbent;
        this.personId = member.person.personId();
    }

    public Member(int personId, Integer memberId, Chamber chamber, boolean incumbent) {
        this.personId = personId;
        this.memberId = memberId;
        this.chamber = chamber;
        this.incumbent = incumbent;
        this.person = null;
    }

    /** --- Overrides --- */

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Member member)) return false;
        return Objects.equals(person, member.person) &&
                Objects.equals(memberId, member.memberId) &&
                chamber == member.chamber &&
                incumbent == member.incumbent;
    }

    @Override
    public int hashCode() {
        return Objects.hash(person.hashCode(), memberId, chamber, incumbent);
    }

    /** --- Getters / Setters --- */

    public Person getPerson() {
        return person;
    }

    public int getMemberId() {
        return memberId;
    }

    public Chamber getChamber() {
        return chamber;
    }

    public Integer getPersonId() {
        return personId;
    }

    public boolean isIncumbent() {
        return this.incumbent;
    }
}
