//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.12 at 11:03:39 AM EST 
//


package gov.nysenate.openleg.xml.calendar;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.nysenate.openleg.jaxb.calendar package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Notes_QNAME = new QName("", "notes");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.nysenate.openleg.jaxb.calendar
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XMLActcaldate }
     * 
     */
    public XMLActcaldate createXMLActcaldate() {
        return new XMLActcaldate();
    }

    /**
     * Create an instance of {@link XMLReleasedate }
     * 
     */
    public XMLReleasedate createXMLReleasedate() {
        return new XMLReleasedate();
    }

    /**
     * Create an instance of {@link XMLSubsponsor }
     * 
     */
    public XMLSubsponsor createXMLSubsponsor() {
        return new XMLSubsponsor();
    }

    /**
     * Create an instance of {@link XMLBill }
     * 
     */
    public XMLBill createXMLBill() {
        return new XMLBill();
    }

    /**
     * Create an instance of {@link XMLCalnos }
     * 
     */
    public XMLCalnos createXMLCalnos() {
        return new XMLCalnos();
    }

    /**
     * Create an instance of {@link XMLSponsor }
     * 
     */
    public XMLSponsor createXMLSponsor() {
        return new XMLSponsor();
    }

    /**
     * Create an instance of {@link XMLCalno }
     * 
     */
    public XMLCalno createXMLCalno() {
        return new XMLCalno();
    }

    /**
     * Create an instance of {@link XMLSequence }
     * 
     */
    public XMLSequence createXMLSequence() {
        return new XMLSequence();
    }

    /**
     * Create an instance of {@link XMLSencalendaractive }
     * 
     */
    public XMLSencalendaractive createXMLSencalendaractive() {
        return new XMLSencalendaractive();
    }

    /**
     * Create an instance of {@link XMLSections }
     * 
     */
    public XMLSections createXMLSections() {
        return new XMLSections();
    }

    /**
     * Create an instance of {@link XMLMotiondate }
     * 
     */
    public XMLMotiondate createXMLMotiondate() {
        return new XMLMotiondate();
    }

    /**
     * Create an instance of {@link XMLReleasetime }
     * 
     */
    public XMLReleasetime createXMLReleasetime() {
        return new XMLReleasetime();
    }

    /**
     * Create an instance of {@link XMLSupplemental }
     * 
     */
    public XMLSupplemental createXMLSupplemental() {
        return new XMLSupplemental();
    }

    /**
     * Create an instance of {@link XMLSencalendar }
     * 
     */
    public XMLSencalendar createXMLSencalendar() {
        return new XMLSencalendar();
    }

    /**
     * Create an instance of {@link XMLSENATEDATA }
     * 
     */
    public XMLSENATEDATA createXMLSENATEDATA() {
        return new XMLSENATEDATA();
    }

    /**
     * Create an instance of {@link XMLCaldate }
     * 
     */
    public XMLCaldate createXMLCaldate() {
        return new XMLCaldate();
    }

    /**
     * Create an instance of {@link XMLSection }
     * 
     */
    public XMLSection createXMLSection() {
        return new XMLSection();
    }

    /**
     * Create an instance of {@link XMLSubbill }
     * 
     */
    public XMLSubbill createXMLSubbill() {
        return new XMLSubbill();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "notes")
    public JAXBElement<String> createNotes(String value) {
        return new JAXBElement<String>(_Notes_QNAME, String.class, null, value);
    }

}
