//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.12 at 11:03:39 AM EST 
//


package gov.nysenate.openleg.xml.calendar;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}bill"/>
 *         &lt;element ref="{}sponsor" minOccurs="0"/>
 *         &lt;element ref="{}subbill" minOccurs="0"/>
 *         &lt;element ref="{}subsponsor" minOccurs="0"/>
 *         &lt;element ref="{}motiondate" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="no" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bill",
    "sponsor",
    "subbill",
    "subsponsor",
    "motiondate"
})
@XmlRootElement(name = "calno")
public class XMLCalno {

    @XmlElement(required = true)
    protected XMLBill bill;
    protected XMLSponsor sponsor;
    protected XMLSubbill subbill;
    protected XMLSubsponsor subsponsor;
    protected XMLMotiondate motiondate;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String no;

    /**
     * Gets the value of the bill property.
     * 
     * @return
     *     possible object is
     *     {@link XMLBill }
     *     
     */
    public XMLBill getBill() {
        return bill;
    }

    /**
     * Sets the value of the bill property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLBill }
     *     
     */
    public void setBill(XMLBill value) {
        this.bill = value;
    }

    /**
     * Gets the value of the sponsor property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSponsor }
     *     
     */
    public XMLSponsor getSponsor() {
        return sponsor;
    }

    /**
     * Sets the value of the sponsor property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSponsor }
     *     
     */
    public void setSponsor(XMLSponsor value) {
        this.sponsor = value;
    }

    /**
     * Gets the value of the subbill property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSubbill }
     *     
     */
    public XMLSubbill getSubbill() {
        return subbill;
    }

    /**
     * Sets the value of the subbill property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSubbill }
     *     
     */
    public void setSubbill(XMLSubbill value) {
        this.subbill = value;
    }

    /**
     * Gets the value of the subsponsor property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSubsponsor }
     *     
     */
    public XMLSubsponsor getSubsponsor() {
        return subsponsor;
    }

    /**
     * Sets the value of the subsponsor property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSubsponsor }
     *     
     */
    public void setSubsponsor(XMLSubsponsor value) {
        this.subsponsor = value;
    }

    /**
     * Gets the value of the motiondate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLMotiondate }
     *     
     */
    public XMLMotiondate getMotiondate() {
        return motiondate;
    }

    /**
     * Sets the value of the motiondate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLMotiondate }
     *     
     */
    public void setMotiondate(XMLMotiondate value) {
        this.motiondate = value;
    }

    /**
     * Gets the value of the no property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNo() {
        return no;
    }

    /**
     * Sets the value of the no property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNo(String value) {
        this.no = value;
    }

}
