//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.12 at 11:03:39 AM EST 
//


package gov.nysenate.openleg.xml.calendar;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}actcaldate" minOccurs="0"/>
 *         &lt;element ref="{}releasedate" minOccurs="0"/>
 *         &lt;element ref="{}releasetime" minOccurs="0"/>
 *         &lt;element ref="{}notes" minOccurs="0"/>
 *         &lt;element ref="{}calnos" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="no" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "actcaldate",
    "releasedate",
    "releasetime",
    "notes",
    "calnos"
})
@XmlRootElement(name = "sequence")
public class XMLSequence {

    protected XMLActcaldate actcaldate;
    protected XMLReleasedate releasedate;
    protected XMLReleasetime releasetime;
    protected String notes;
    protected XMLCalnos calnos;
    @XmlAttribute(required = true)
    protected String no;

    /**
     * Gets the value of the actcaldate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLActcaldate }
     *     
     */
    public XMLActcaldate getActcaldate() {
        return actcaldate;
    }

    /**
     * Sets the value of the actcaldate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLActcaldate }
     *     
     */
    public void setActcaldate(XMLActcaldate value) {
        this.actcaldate = value;
    }

    /**
     * Gets the value of the releasedate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLReleasedate }
     *     
     */
    public XMLReleasedate getReleasedate() {
        return releasedate;
    }

    /**
     * Sets the value of the releasedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLReleasedate }
     *     
     */
    public void setReleasedate(XMLReleasedate value) {
        this.releasedate = value;
    }

    /**
     * Gets the value of the releasetime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLReleasetime }
     *     
     */
    public XMLReleasetime getReleasetime() {
        return releasetime;
    }

    /**
     * Sets the value of the releasetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLReleasetime }
     *     
     */
    public void setReleasetime(XMLReleasetime value) {
        this.releasetime = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the calnos property.
     * 
     * @return
     *     possible object is
     *     {@link XMLCalnos }
     *     
     */
    public XMLCalnos getCalnos() {
        return calnos;
    }

    /**
     * Sets the value of the calnos property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLCalnos }
     *     
     */
    public void setCalnos(XMLCalnos value) {
        this.calnos = value;
    }

    /**
     * Gets the value of the no property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNo() {
        return no;
    }

    /**
     * Sets the value of the no property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNo(String value) {
        this.no = value;
    }

}
